name: Auto_Lotto

on:
  schedule:
    - cron: 30 9 * * 1
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: Windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Pip
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot selenium
    #    if [ -f N_text.txt ]; then pip install -r N_text; fi
    - name: run
      run: |
        python Auto_Buy.py
